language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require hirak/prestissimo

install: 
  - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit -v

jobs:
  include:
    - stage: Test
      php: 7.1
      name: prefer-lowest
      install:
        - composer remove --dev friendsofphp/php-cs-fixer phpstan/phpstan --no-update
        - composer require --dev phpunit/phpunit:^6.5.14 --no-update
        - travis_retry travis_wait composer install --no-interaction --prefer-dist
        - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
    - name: sentry/sentry dev-develop
      install: composer require sentry/sentry:dev-develop
    - stage: Code style and static analysis
      script:
        - composer phpstan
      env: PHPSTAN=true
    - script: 
        - composer cs-check
      env: CS-FIXER=true
    - stage: coverage
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/cd75fa32-e67c-11e9-8af5-9a14aa75c5d9/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
after_script:
  - npm install -g @zeus-ci/cli
  - zeus upload -t "mime/type" path/to/artifact
