language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini || echo "Can't disable xDebug"
  - |
    if [ "$SYMFONY_VERSION" != "" ]; then
      sed -ri '/symfony\/(http-client|monolog-bundle)/! s/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
    fi;
  - composer self-update
  - composer global require hirak/prestissimo

install: 
  - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable

script:
  - vendor/bin/phpunit -v

jobs:
  include:
    - stage: Test
      php: 7.1
      env: 
      - SYMFONY_VERSION: 3.4.*
      - SYMFONY_DEPRECATIONS_HELPER: disabled
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.0.*
    - name: prefer-lowest
      install:
        - travis_retry travis_wait composer install --no-interaction --prefer-dist
        - composer remove --dev friendsofphp/php-cs-fixer phpstan/phpstan phpstan/phpstan-phpunit jangregor/phpstan-prophecy --no-update
        - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest
    - stage: Code style and static analysis
      name: PHPStan
      php: 7.4
      script:
        - composer phpstan
    - script: 
        - composer cs-check
      name: PHP-CS-Fixer
    - stage: coverage
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT
  allow_failures:
    - name: sentry/sentry dev-develop
      stage: Test
      install: composer require sentry/sentry:dev-develop

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/cd75fa32-e67c-11e9-8af5-9a14aa75c5d9/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
after_script:
  - npm install -g @zeus-ci/cli
  - zeus upload -t "mime/type" path/to/artifact
