language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer global require hirak/prestissimo

install:
  # - '[ "$LOCK_FILE" == "" ] || [ ! -f "$LOCK_FILE" ] || cp "$LOCK_FILE" ./composer.lock'
  - composer install --prefer-dist
  - composer remove friendsofphp/php-cs-fixer
  - travis_retry travis_wait composer update --no-interaction --prefer-dist --prefer-stable $COMPOSER_OPTIONS

script:
  - vendor/bin/phpunit -v

jobs:
  include:
    - stage: test
      php: 5.6
      env: COMPOSER_OPTIONS="--prefer-lowest" LOCK_FILE="./build/composer-5.6-lowest.lock"
    - stage: Test
      php: 7.0
      env: COMPOSER_OPTIONS="--prefer-lowest" LOCK_FILE="./build/composer-7.0-lowest.lock"
    - stage: codestyle and SCA
      php: 7.1
      script:
        - composer require --dev phpstan/phpstan symfony/expression-language --no-interaction --prefer-dist --prefer-stable
        - vendor/bin/phpstan analyse src --level 7 -c phpstan.neon
      env: PHPSTAN=true
    - script: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
      env: CS-FIXER=true
    - stage: coverage
      php: 7.1
      script: 
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
      after_success:
        - vendor/bin/ocular code-coverage:upload --format=php-clover clover.xml --revision=$TRAVIS_COMMIT
